kind: pipeline
name: default

platform:
  arch: amd64

steps:
  - name: lint
    image: golang
    commands:
      - go get -u golang.org/x/lint/golint
      - golint

  - name: test
    image: golang
    commands:
      - go test -v .

  - name: coverage
    image: golang
    environment:
      COVERALLS_TOKEN:
        from_secret: COVERALLS_TOKEN
    commands:
      - go get github.com/mattn/goveralls
      - goveralls -service drone.io
    when:
      branch:
        - master
      event:
        - push
