kind: pipeline
name: default

platform:
  arch: amd64

steps:
  - name: test
    image: golang
    environment:
      COVERALLS_TOKEN:
        from_secret: COVERALLS_TOKEN
    commands:
      - curl ifconfig.me
      - go get github.com/mattn/goveralls
      - goveralls -service drone.io
